### ISSUE TITLE
Process halt after run telegram-cli

### ISSUE THREAD

**Issue by l0rdx3n0** [b3vis/telegram-cli#2]
Hi b3vis,

I follow your instructions and the problem is that telegramCLI container is rebooting every time.

Checking the logs and obtain always the same results:
```
telegramCLI       | change_user_group: can't find the user telegramd to switch to
telegramCLI       | Telegram-cli version 1.3.1, Copyright (C) 2013-2015 Vitaly Valtman
telegramCLI       | Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
telegramCLI       | This is free software, and you are welcome to redistribute it
telegramCLI       | under certain conditions; type `show_license' for details.
telegramCLI       | Telegram-cli uses libtgl version 2.0.1
telegramCLI       | I: config dir=[/root/.telegram-cli]
telegramCLI       | > > All done. Exit
telegramCLI       | halt
```

My docker-compose status for this container is always the same:
```
telegramCLI     /usr/bin/telegr ...   Restarting
```

Could you tell me if the entrypoint for this docker is correct?
Did you use another telegram-cli argument?

Thanks in advance.

Regards, Juan.

**Comment by b3vis** [comment]
Hi Juan,

I just tested this container on Docker for Mac using the `docker run...` command from my instructions and it worked first time for me. I too get the 'cant find the user telegramd to switch to' warning but I don't think it's a problem. 

The problem may be where you're trying to run it within docker-compose as I wrote this container to be ran interactively using docker run.

Thanks,
b3vis
