### ISSUE TITLE
exec

### ISSUE THREAD

**Issue by cafefars** [b3vis/telegram-cli#3]
Hello
Run telegram-cli as a service

$ docker run -it --rm \
      --name=telegram-cli \
      -v /path/to/telegram-cli:/root/.telegram-cli \
      b3vis/telegram-cli
How to run command with exec ?

~$ docker exec telegram-cli contact-list

OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"contact-list\": executable file not found in $PATH": unknown

**Comment by cafefars** [comment]
Sorry to be corrected
Run as a service
docker run -d -it --name=telegram-cli -v /home/cafefars/telegram:/root/.telegram-cli b3vis/telegram-cli

**Comment by b3vis** [comment]
I take it you worked out how to do this as you closed the issue
